stages:
  - build
  - deploy

build:
  image: ubuntu:20.04
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y && apt-get install -y curl ca-certificates software-properties-common make
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - make build
  only:
    - main


deploy:
  image: ubuntu:20.04
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp ./pull.sh $SSH_USER@$VM_IPADDRESS:/tmp
    - ssh $SSH_USER@$VM_IPADDRESS dos2unix /tmp/pull.sh
    - ssh $SSH_USER@$VM_IPADDRESS chmod +x /tmp/pull.sh
    - ssh $SSH_USER@$VM_IPADDRESS /tmp/pull.sh

  only:
    - main